export const SCIENCE_JOKES = [
  'What did the asteroid say when asked a question? "No comet."',
  'Who was the smartest pig? Ein-swine.',
  'What does a magician shout during an experiment? Labracadabra!',
  'What did the bartender say to the neutron? "For you, no charge."',
  'Why did the biology student break up with the physics student? There was no chemistry.',
  'I tried to come up with a chemistry joke... but all the good ones Argon.',
  "Why can't you trust an atom? They make up everything.",
  'What do you call an acid with an attitude? A-mean-o acid.',
  "What's a pirate's favorite amino acid? Arrr-ginine!",
  "What is a physicist's favorite food? Fission chips.",
  "What do you do with a dead chemist? You barium.",
  "What do you do with sick chemists? Helium.",
  "Organic chemistry is difficult. Those who study it have alkynes of trouble.",
  "If the silver surfer and iron man teamed up, they'd be alloys.",
  "Why are chemists great at solving problems? Because they have all the solutions.",
  "A photon checks into a hotel and is asked if he needs help with his luggage. He says, 'No, I'm traveling light.'",
  "Why do biologists look forward to casual Friday? Because they can wear their favorite genes.",
  "Two chemists go into a bar. The first one says 'I think I'll have an H2O.' The second says 'I'll have an H2O too.' He died.",
  "Anybody know any jokes about sodium? NaBrO.",
  "How do you know the moon is going broke? It's down to its last quarter.",
  "Why was the math book sad? Because it had too many problems.",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I think I've lost an electron. 'Are you sure?' Yes, I'm positive.",
  "Why do plants hate maths? Because it gives them square roots.",
  "What did the scientist say when he found 2 helium atoms? HeHe",
  "What do you call a biologist’s self-portrait? A cell-fie.",
  "Why did the girl break up with the biologist? He was too cell-fish.",
  "What's the fastest way to determine the sex of a chromosome? Pull down its genes.",
  "Why did the mushroom get invited to all the parties? Because he's a fungi!",
  "No matter how popular they get, antibiotics will never be viral.",
  "Do you know what gets on my nerves? Myelin.",
  "Biology is the only science where multiplication is the same thing as division.",
  "Where did the viruses go? They flu away.",
  "Why can't you trust atoms? They make up everything.",
  "How do astronomers organize a party? They planet!",
  "I just read a book about Helium. It was so good that I can't put it down.",
  "Why did the physicist break up with the biologist? There was no chemistry.",
  "Why did the scientist take out his doorbell? He wanted to win the no-bell prize.",
  "Why didn’t the skeleton go to the ball? He had no body to go with.", 
  "Why didn’t the skeleton cross the road? He didn't have the guts",
  "What type of fish is made of two sodium atoms? 2 Na"
];
