export const SCIENCE_JOKES = [
  'What did the asteroid say when asked a question? "No comet."',
  'Who was the smartest pig? Ein-swine.',
  'What does a magician shout during an experiment? Labracadabra!',
  'What did the bartender say to the neutron? "For you, no charge."',
  'Why did the biology student break up with the physics student? There was no chemistry.',
  'I tried to come up with a chemistry joke... but all the good ones Argon.',
  "Why can't you trust an atom? They make up everything.",
  'What do you call an acid with an attitude? A-mean-o acid.',
  'Why did the cell phone go to school? To improve its cell culture.',
  "Helium walks into a bar. Bartender: \"We don't serve noble gases.\" He doesn't react.",
  "What's a pirate's favorite amino acid? Arrr-ginine!",
  "What is a physicist's favorite food? Fission chips.",
  "How does a mathematician fix a flat tire? With a multi-plyer.",
  "What do you do with a dead chemist? You barium.",
  "Why did the bacteria cross the microscope? To get to the other slide.",
  "Organic chemistry is difficult. Those who study it have alkynes of trouble.",
  "If the silver surfer and iron man teamed up, they'd be alloys.",
  "Why are chemists great at solving problems? Because they have all the solutions.",
  "Did you hear about the famous microbiologist? He was a man of many cultures.",
  "What did the thermometer say to the graduated cylinder? You may have graduated, but I've got many degrees.",
  "A photon checks into a hotel and is asked if he needs help with his luggage. He says, 'No, I'm traveling light.'",
  "Why do biologists look forward to casual Friday? Because they can wear their genes.",
  "Two chemists go into a bar. The first one says 'I think I'll have an H2O.' The second says 'I'll have an H2O too.' And he died.",
  "Anybody know any jokes about sodium? Na.",
  "I told a chemistry joke... there was no reaction.",
  "How do you know the moon is going broke? It's down to its last quarter.",
  "Why was the math book sad? Because it had too many problems.",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I think I've lost an electron. 'Are you sure?' Yes, I'm positive.",
  "What does a subatomic duck say? Quark!",
  "Why do plants hate maths? Because it gives them square roots.",
  "What do you call a tooth in a glass of water? A one molar solution.",
  "Why did the white bear dissolve in water? Because it was polar.",
  "What did the scientist say when he found 2 isotopes of helium? HeHe",
  "Why do researchers look forward to Fridays? Because they get to go to the bar graph.",
  "What do you call a biologist’s self-portrait? A cell-fie.",
  "Why was the free-body diagram so stressed? It had too much tension.",
  "Did you hear about the biologist who had twins? She named one Jessica and the other Control.",
  "Why did the girl break up with the biologist? He was too cell-fish.",
  "What's the fastest way to determine the sex of a chromosome? Pull down its genes.",
  "Why did the mushroom get invited to all the parties? Because he's a fungi!",
  "Did you hear oxygen went on a date with potassium? It went OK.",
  "What did the scientist wear to keep warm? A thermal cycler.",
  "Are you made of fluorine, iodine, and neon? Because you are F-I-Ne.",
  "How do you keep warm in a cold room? You go to the corner, because it's usually 90 degrees.",
  "Why did the two 4s skip lunch? Because they already 8.",
  "What did one tectonic plate say when he bumped into another? Sorry, my fault!",
];
