
import { NotebookText, LucideDotSquare, FlaskConical, Glasses, Zap, Snowflake, Columns2 } from 'lucide-react';

export const FONT_SIZES = [
  { label: 'Small', value: '14px' },
  { label: 'Medium', value: '16px' },
  { label: 'Large', value: '18px' },
  { label: 'XL', value: '20px' },
];

export const APP_THEMES = {
  // ── Curated ──
  default: {
    label: 'Lab Default',
    icon: FlaskConical,
    group: 'special',
    bg: 'linear-gradient(135deg, #f0f4f8 0%, #e8edf5 40%, #eef2f7 100%)',
    cardBg: 'bg-white/80 backdrop-blur',
    cardBorder: 'border-slate-200/60',
    textPrimary: 'text-slate-800',
    textSecondary: 'text-slate-500',
    headerClass: '',
    bodyClass: '',
    iconStyle: null,
  },
  notes: {
    label: 'Notes',
    icon: NotebookText,
    group: 'special',
    bg: '#faf8f3',
    cardBg: 'bg-[##d4b4238f)]',
    cardBorder: 'border-amber-200/80',
    textPrimary: 'text-stone-800',
    textSecondary: 'text-stone-500',
    headerClass: 'notes-theme',
    bodyClass: 'notes-theme',
    iconStyle: { background: 'linear-gradient(135deg, #b5a07a 0%, #8c7a5e 100%)' },
  },
  monochrome: {
    label: 'Monochrome',
    icon: LucideDotSquare,
    group: 'special',
    bg: '#f2f2f2',
    cardBg: 'bg-white',
    cardBorder: 'border-neutral-300',
    textPrimary: 'text-neutral-900',
    textSecondary: 'text-neutral-500',
    headerClass: 'mono-theme',
    bodyClass: 'mono-theme',
    iconStyle: { background: 'linear-gradient(135deg, #555 0%, #222 100%)' },
  },
  minimal: {
    label: 'Minimal White',
    icon: Snowflake,
    group: 'special',
    bg: '#ffffff',
    cardBg: 'bg-gray-50',
    cardBorder: 'border-gray-200',
    textPrimary: 'text-gray-900',
    textSecondary: 'text-gray-500',
    headerClass: '',
    bodyClass: '',
    iconStyle: { background: 'linear-gradient(135deg, #9ca3af 0%, #6b7280 100%)' },
  },
  modern: {
    label: 'Modern Dark',
    icon: Zap,
    group: 'special',
    bg: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    cardBg: 'bg-white/5 backdrop-blur-xl',
    cardBorder: 'border-white/10',
    textPrimary: 'text-white',
    textSecondary: 'text-blue-300',
    headerClass: 'dark-theme',
    bodyClass: 'dark-theme',
    isDark: true,
    iconStyle: { background: 'linear-gradient(135deg, #3b5bdb 0%, #1e40af 100%)' },
  },
  macosGlass: {
    label: 'MacOS Glass',
    icon: Glasses,
    group: 'special',
    bg: 'linear-gradient(135deg, #e2e8f0 0%, #cbd5e1 50%, #94a3b8 100%)',
    cardBg: 'bg-white/30 backdrop-blur-2xl',
    cardBorder: 'border-white/40',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-600',
    headerClass: 'glass-theme',
    bodyClass: 'glass-theme',
    isGlass: true,
    iconTextColor: 'text-black',
    iconStyle: { background: 'rgba(255, 255, 255, 0.4)', backdropFilter: 'blur(10px)', border: '1px solid rgba(255, 255, 255, 0.5)' },
  },
  pride: {
    label: 'LGBTQ+',
    emoji: '🏳️‍🌈',
    group: 'special',
    bg: 'linear-gradient(45deg, #fce7f3 0%, #e0e7ff 50%, #d1fae5 100%)',
    cardBg: 'bg-white/80 backdrop-blur',
    cardBorder: 'border-slate-200/60',
    textPrimary: 'text-slate-800',
    textSecondary: 'text-slate-500',
    headerClass: 'pride-theme',
    bodyClass: 'pride-theme',
    iconTextColor: 'text-black',
    iconStyle: { background: 'linear-gradient(45deg, #ff0000, #ff8000, #ffff00, #00ff00, #0000ff, #8000ff)' },
  },
  highContrast: {
    label: 'Black/White',
    icon: Columns2,
    group: 'special',
    bg: '#ffffff',
    cardBg: 'bg-white',
    cardBorder: 'border-black border-4',
    textPrimary: 'text-black font-black',
    textSecondary: 'text-black font-bold',
    headerClass: 'hc-theme',
    bodyClass: 'hc-theme',
    iconStyle: { background: '#000000', border: '1px solid white' },
  },
  // ── Muted tones ─────────────────────────────────────────────────────────────
  steel: {
    label: 'Steel Blue',
    group: 'muted',
    bg: '#e8f0f3',
    cardBg: 'bg-[#f4f8fa]',
    cardBorder: 'border-[#aec8d2]',
    textPrimary: 'text-[#2c4a54]',
    textSecondary: 'text-[#5a8294]',
    headerClass: '',
    bodyClass: '',
    iconStyle: { background: 'linear-gradient(135deg, #79a2b0 0%, #4e7f90 100%)' },
  },
  ash: {
    label: 'Ash Gray',
    group: 'muted',
    bg: '#e9ebea',
    cardBg: 'bg-[#f5f6f5]',
    cardBorder: 'border-[#b2beb5]',
    textPrimary: 'text-[#2e3330]',
    textSecondary: 'text-[#848884]',
    headerClass: '',
    bodyClass: '',
    iconStyle: { background: 'linear-gradient(135deg, #848884 0%, #5a5f5c 100%)' },
  },
  charcoal: {
    label: 'Charcoal',
    group: 'muted',
    bg: '#d8dfe2',
    cardBg: 'bg-[#edf0f1]',
    cardBorder: 'border-[#9aacb4]',
    textPrimary: 'text-[#36454f]',
    textSecondary: 'text-[#5c7480]',
    headerClass: '',
    bodyClass: '',
    iconStyle: { background: 'linear-gradient(135deg, #36454f 0%, #1e2d35 100%)' },
  },
  sage: {
    label: 'Sage',
    group: 'muted',
    bg: '#e4ebe6',
    cardBg: 'bg-[#f2f6f3]',
    cardBorder: 'border-[#a8bfac]',
    textPrimary: 'text-[#2d3d30]',
    textSecondary: 'text-[#5a7a5e]',
    headerClass: '',
    bodyClass: '',
    iconStyle: { background: 'linear-gradient(135deg, #6b8f71 0%, #4a6b50 100%)' },
  },
  dusk: {
    label: 'Dusk',
    group: 'muted',
    bg: '#e5e3ee',
    cardBg: 'bg-[#f3f2f8]',
    cardBorder: 'border-[#b4afd0]',
    textPrimary: 'text-[#2e2b42]',
    textSecondary: 'text-[#6b6590]',
    headerClass: '',
    bodyClass: '',
    iconStyle: { background: 'linear-gradient(135deg, #7b75a8 0%, #4e4878 100%)' },
  },
  sand: {
    label: 'Sand',
    group: 'muted',
    bg: '#ede8de',
    cardBg: 'bg-[#f7f4ee]',
    cardBorder: 'border-[#c9bfa8]',
    textPrimary: 'text-[#3d3628]',
    textSecondary: 'text-[#7a6e58]',
    headerClass: '',
    bodyClass: '',
    iconStyle: { background: 'linear-gradient(135deg, #9c8c70 0%, #6e6050 100%)' },
  },
  dark: {
    label: 'Dark',
    group: 'muted',
    bg: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
    cardBg: 'bg-slate-800/80 backdrop-blur',
    cardBorder: 'border-slate-700/60',
    textPrimary: 'text-slate-100',
    textSecondary: 'text-slate-400',
    headerClass: 'dark-theme',
    bodyClass: 'dark-theme',
    isDark: true,
    iconStyle: { background: 'linear-gradient(135deg, #475569 0%, #334155 100%)' },
  },
  girlyPink: {
    label: 'Girly Pink',
    group: 'muted',
    bg: '#fff0f6',
    cardBg: 'bg-white/90',
    cardBorder: 'border-pink-200',
    textPrimary: 'text-pink-900',
    textSecondary: 'text-pink-500',
    headerClass: 'pink-theme',
    bodyClass: 'pink-theme',
    iconStyle: { background: 'linear-gradient(135deg, #ff85c0 0%, #f759ab 100%)' },
  },
};
